---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-media-repo
  namespace: comms
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-media-repo
      version: 1.0.6
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: matrix-synapse
      namespace: comms
  values:
    image:
      repository: turt2live/matrix-media-repo
      tag: v1.2.8

    config:
      datastores:
        - type: s3
          enabled: true
          forKinds: ["all"]
          opts:
            tempPath: "/tmp/mediarepo_s3_upload"
            ssl: false
            bucketName: matrix-media
            endpoint: rook-ceph-rgw-object-store.rook-ceph.svc
            accessKeyId: ${SECRET_MATRIX_MEDIA_S3_ACCESS_KEY_ID}
            accessSecret: ${SECRET_MATRIX_MEDIA_S3_ACCESS_SECRET}

    admins:
      - "@ryan:k8s-at-home.com"

    homeservers:
      "matrix.k8s-at-home.com":
        csApi: 'http://matrix-synapse:8008'
        backoffAt: 10
        adminApiKind: 'matrix'
        identicons:
          enabled: false

    ingress:
      enabled: true
      className: traefik
      annotations:
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.k8s-at-home.com"
      hosts:
        - host: matrix.k8s-at-home.com
          paths:
            - "/_matrix/media"
      tls:
        - secretName: matrix-cert
          hosts:
            - matrix.k8s-at-home.com

    postgresql:
      enabled: true
      sslMode: disable
      postgresqlPassword: ${SECRET_MATRIX_POSTGRESQL_PASSWORD}
      postgresqlUsername: synapse
      postgresqlDatabase: synapse
      persistence:
        enabled: true
        existingClaim: matrix-media-repo-postgresql-pvc

    persistence:
      enabled: false
